version: '3.8'
services:
  movies:
    image: balu699/projmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: balu699/projtrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  recharge:
    image: balu699/projrecharge:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  dth:
    image: balu699/projdth:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
